// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baxwnngcuaojniihxyaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheHdubmdjdWFvam5paWh4eWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDQ5ODQsImV4cCI6MjA2MzEyMDk4NH0.BDFpdAuviN-Q5xbH9X1xiayHFrdXui9-3yMnErEsOIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);